services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev 
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev 
    ports:
      - "80:5173" 
    volumes:
      - ./frontend:/app 
      - /app/node_modules 

  postgres:
    ports:
      - "5432:5432" 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8081:80"
    networks:
      - acadmap-net
    depends_on:
      postgres:
        condition: service_healthy