version: '3.8'

networks:
  acadmap-net:
    name: acadmap-net

volumes:
  postgres-vol:
    name: postgres-vol

services:
  backend:
    build: ./backend
    container_name: acadmap-backend
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/dev"
      SPRING_DATASOURCE_USERNAME: "usuario"
      SPRING_DATASOURCE_PASSWORD: "87654321"
    networks:
      - acadmap-net
    
  frontend:
    build: ./frontend
    container_name: acadmap-frontend
    ports:
      - 80:5173
    networks:
      - acadmap-net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: dev
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./backend/docker-volumes/scripts-sql:/docker-entrypoint-initdb.d
    # ports:
    #   - "5432:5432"
    networks:
      - acadmap-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8081:80"
    networks:
      - acadmap-net
    depends_on:
      postgres:
        condition: service_healthy
