# docker-compose.yml
version: '3.8'

networks:
  acadmap-net:
    name: acadmap-net

volumes:
  postgres-vol:
    name: postgres-vol

services:
  backend:
    container_name: acadmap-backend
    restart: on-failure
    networks:
      - acadmap-net
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/dev"
      SPRING_DATASOURCE_USERNAME: "usuario"
      SPRING_DATASOURCE_PASSWORD: "87654321"

  frontend:
    container_name: acadmap-frontend
    restart: always
    networks:
      - acadmap-net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./backend/docker-volumes/scripts-sql:/docker-entrypoint-initdb.d
    networks:
      - acadmap-net
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d dev"]
      interval: 10s
      timeout: 5s
      retries: 5