-- Inserções para a tabela AreaPesquisa
INSERT INTO AreaPesquisa (id_area_pesquisa, nome) 
VALUES 
(gen_random_uuid(), 'Matemática'),
(gen_random_uuid(), 'Probabilidade e Estatística'),
(gen_random_uuid(), 'Ciência da Computação'),
(gen_random_uuid(), 'Astronomia'),
(gen_random_uuid(), 'Física'),
(gen_random_uuid(), 'Química'),
(gen_random_uuid(), 'Geociências'),
(gen_random_uuid(), 'Oceanografia'),
(gen_random_uuid(), 'Biologia Geral'),
(gen_random_uuid(), 'Genética'),
(gen_random_uuid(), 'Botânica'),
(gen_random_uuid(), 'Zoologia'),
(gen_random_uuid(), 'Ecologia'),
(gen_random_uuid(), 'Morfologia'),
(gen_random_uuid(), 'Fisiologia'),
(gen_random_uuid(), 'Bioquímica'),
(gen_random_uuid(), 'Biofísica'),
(gen_random_uuid(), 'Farmacologia'),
(gen_random_uuid(), 'Imunologia'),
(gen_random_uuid(), 'Microbiologia'),
(gen_random_uuid(), 'Parasitologia'),
(gen_random_uuid(), 'Engenharia Civil'),
(gen_random_uuid(), 'Engenharia de Minas'),
(gen_random_uuid(), 'Engenharia de Materiais e Metalúrgica'),
(gen_random_uuid(), 'Engenharia Elétrica'),
(gen_random_uuid(), 'Engenharia Mecânica'),
(gen_random_uuid(), 'Engenharia Química'),
(gen_random_uuid(), 'Engenharia Sanitária'),
(gen_random_uuid(), 'Engenharia de Produção'),
(gen_random_uuid(), 'Engenharia Nuclear'),
(gen_random_uuid(), 'Engenharia de Transportes'),
(gen_random_uuid(), 'Engenharia Naval e Oceânica'),
(gen_random_uuid(), 'Engenharia Aeroespacial'),
(gen_random_uuid(), 'Engenharia Biomédica'),
(gen_random_uuid(), 'Engenharia Agrícola'), -- Nota: Aparece duas vezes na sua lista, inserindo uma vez.
(gen_random_uuid(), 'Medicina'),
(gen_random_uuid(), 'Odontologia'),
(gen_random_uuid(), 'Farmácia'),
(gen_random_uuid(), 'Enfermagem'),
(gen_random_uuid(), 'Nutrição'),
(gen_random_uuid(), 'Saúde Coletiva'),
(gen_random_uuid(), 'Fonoaudiologia'),
(gen_random_uuid(), 'Fisioterapia e Terapia Ocupacional'),
(gen_random_uuid(), 'Educação Física'),
(gen_random_uuid(), 'Agronomia'),
(gen_random_uuid(), 'Recursos Florestais e Engenharia Florestal'),
(gen_random_uuid(), 'Zootecnia'),
(gen_random_uuid(), 'Medicina Veterinária'),
(gen_random_uuid(), 'Recursos Pesqueiros e Engenharia de Pesca'),
(gen_random_uuid(), 'Ciência e Tecnologia de Alimentos'),
(gen_random_uuid(), 'Direito'),
(gen_random_uuid(), 'Administração'),
(gen_random_uuid(), 'Economia'),
(gen_random_uuid(), 'Arquitetura e Urbanismo'),
(gen_random_uuid(), 'Planejamento Urbano e Regional'),
(gen_random_uuid(), 'Demografia'),
(gen_random_uuid(), 'Ciência da Informação'),
(gen_random_uuid(), 'Comunicação'),
(gen_random_uuid(), 'Serviço Social'),
(gen_random_uuid(), 'Economia Doméstica'),
(gen_random_uuid(), 'Turismo'),
(gen_random_uuid(), 'Desenho Industrial'),
(gen_random_uuid(), 'Filosofia'),
(gen_random_uuid(), 'Sociologia'),
(gen_random_uuid(), 'Antropologia e Arqueologia'),
(gen_random_uuid(), 'História'),
(gen_random_uuid(), 'Geografia'),
(gen_random_uuid(), 'Psicologia'),
(gen_random_uuid(), 'Educação'),
(gen_random_uuid(), 'Ciência Política'),
(gen_random_uuid(), 'Teologia'),
(gen_random_uuid(), 'Linguística'),
(gen_random_uuid(), 'Letras'),
(gen_random_uuid(), 'Artes');

-- Inserções para a tabela Programa
INSERT INTO Programa (id_programa, nome) VALUES 
(gen_random_uuid(), 'programa de pós-graduação em matemática em rede nacional - profmat'),
(gen_random_uuid(), 'programa de pós-graduação em cidades, territórios, identidades e educação - ppgcite'),
(gen_random_uuid(), 'programa de pós-graduação em biodiversidade e conservação - ppgbc'),
(gen_random_uuid(), 'programa de pós-graduação educação escolar indígena - ppgeei(em associação: uepa sede - ufpa - ufopa - unifesspa)'),
(gen_random_uuid(), 'programa de pós-graduação em etnodiversidade - ppgetno'),
(gen_random_uuid(), 'programa de pós-graduação em ensino de geografia - profgeo'),
(gen_random_uuid(), 'programa de pós-graduação em ensino de história - profhistoria'),
(gen_random_uuid(), 'programa de pós-graduação em ciência e engenharia de materiais - ppgcem'),
(gen_random_uuid(), 'programa de pós-graduação em linguagem e saberes na amazônia - pplsa'),
(gen_random_uuid(), 'programa de pós-graduação em biologia ambiental - ppba'),
(gen_random_uuid(), 'programa de pós-graduação em estudos da linguagem - ppgel'),
(gen_random_uuid(), 'programa de pós-graduação em educação e cultura - ppgeduc'),
(gen_random_uuid(), 'programa de pós-graduação em ciência animal - ppgcan'),
(gen_random_uuid(), 'programa de pós-graduação em estudos antrópicos na amazônia - ppgeaa'),
(gen_random_uuid(), 'programa de pós-graduação em saúde animal na amazônia - ppgsaam'),
(gen_random_uuid(), 'programa de pós-graduação em reprodução animal na amazônia (ufra) - reproamazon'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia de barragem e gestão ambiental - pebga'),
(gen_random_uuid(), 'programa de pós-graduação em computação aplicada - ppca'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia de infraestrutura e desenvolvimento energético - ppginde'),
(gen_random_uuid(), 'programa de pós-graduação criatividade e inovação em metodologias de ensino superior - ppgcimes'),
(gen_random_uuid(), 'programa de pós-graduação em neurociências e biologia celular - pnbc'),
(gen_random_uuid(), 'programa de pós-graduação em genética e biologia molecular - ppgbm'),
(gen_random_uuid(), 'programa de pós-graduação em zoologia - ppgzool'),
(gen_random_uuid(), 'programa de pós-graduação em biologia de agentes infecciosos e parasitários - ppgbaip'),
(gen_random_uuid(), 'programa de pós-graduação em ecologia aquática e pesca - ppgeap'),
(gen_random_uuid(), 'programa de pós-graduação em biotecnologia - ppgbiotec'),
(gen_random_uuid(), 'programa de pós-graduação em ecologia - ppgeco'),
(gen_random_uuid(), 'programa de pós-graduação em biodiversidade e biotecnologia - bionorte'),
(gen_random_uuid(), 'programa de pós graduação em ensino de biologia - profbio'),
(gen_random_uuid(), 'programa de pós-graduação em análises clínicas - macpro'),
(gen_random_uuid(), 'programa de pós-graduação em farmacologia e bioquímica - farmabio'),
(gen_random_uuid(), 'programa de pós-graduação em educação - ppged'),
(gen_random_uuid(), 'programa de pós-graduação em artes - ppgartes'),
(gen_random_uuid(), 'programa de pós-graduação no ensino de artes - profartes'),
(gen_random_uuid(), 'programa de pós-graduação em odontologia - ppgo'),
(gen_random_uuid(), 'programa de pós-graduação inter-institucional em enfermagem - dinter ufpa/ufsc'),
(gen_random_uuid(), 'programa de pós-graduação em enfermagem - ppgenf'),
(gen_random_uuid(), 'programa de pós-graduação em ciências farmacêuticas - ppgcf'),
(gen_random_uuid(), 'programa de pós-graduação em inovação farmacêuticas - ppgif'),
(gen_random_uuid(), 'programa de pós-graduação em saúde coletiva na amazônia'),
(gen_random_uuid(), 'programa de pós-graduação em assistência farmacêutica - ppgaf'),
(gen_random_uuid(), 'programa de pós-graduação ciências do movimento humano - ppgcmh'),
(gen_random_uuid(), 'programa de pós-graduação em atenção e estudo clínico no diabetes - ppgdiabetes'),
(gen_random_uuid(), 'programa de pós-graduação em química medicinal e modelagem molecular - ppgqmmm'),
(gen_random_uuid(), 'programa de pós-graduação em ciência da computação - ppgcc'),
(gen_random_uuid(), 'programa de pós-graduação em matemática e estatística - ppgme'),
(gen_random_uuid(), 'programa de pós-graduação em física - ppgf'),
(gen_random_uuid(), 'programa de pós-graduação em química - ppgq'),
(gen_random_uuid(), 'programa de pós-graduação em matemática doutorado - pdm'),
(gen_random_uuid(), 'programa de pós-graduação em matemática (mestrado profissional) - profmat'),
(gen_random_uuid(), 'programa de pós-graduação em ciências e meio ambiente - ppgcma'),
(gen_random_uuid(), 'programa de pós-graduação em ensino de física - profis/mnpef'),
(gen_random_uuid(), 'programa de pós-graduação em direito - ppgd'),
(gen_random_uuid(), 'programa de pós-graduação em direito e desenvolvimento na amazônia - ppgdda'),
(gen_random_uuid(), 'programa de pós-graduação em serviço social - ppgss'),
(gen_random_uuid(), 'programa de pós-graduação em economia - ppge'),
(gen_random_uuid(), 'pós-graduação em ciência da informação - ppgci'),
(gen_random_uuid(), 'programa de pós-graduação economia aplicada - ppgea'),
(gen_random_uuid(), 'programa de pós-graduação em contabilidade - ppgc'),
(gen_random_uuid(), 'programa de pós-graduação em administração - ppgad'),
(gen_random_uuid(), 'programa de pós-graduação em educação em ciências e matemáticas - ppgecm'),
(gen_random_uuid(), 'programa de pós-graduação em docência em educação em ciências e matemáticas - ppgdoc'),
(gen_random_uuid(), 'programa de pós-graduação em educação em ciências e matemática - ppgecem (ufmt - ufpa - uea)'),
(gen_random_uuid(), 'programa de pós-graduação em antropologia - ppga'),
(gen_random_uuid(), 'programa de pós-graduação em história - pphist'),
(gen_random_uuid(), 'programa de pós-graduação em ciência política - ppgcp'),
(gen_random_uuid(), 'programa de pós-graduação em geografia - ppgeo'),
(gen_random_uuid(), 'programa de pós-graduação em psicologia - ppgp'),
(gen_random_uuid(), 'programa de pós-graduação em filosofia - ppgfil'),
(gen_random_uuid(), 'programa de pós-graduação em segurança pública - ppgsp'),
(gen_random_uuid(), 'programa de pós-graduação em sociologia e antropologia - ppgsa'),
(gen_random_uuid(), 'programa de pós-graduação em geofísica - cpgf'),
(gen_random_uuid(), 'programa de pós-graduação em geologia e geoquímica - ppgg'),
(gen_random_uuid(), 'programa de pós-graduação em ciências ambientais - ppgca'),
(gen_random_uuid(), 'programa de pós-graduação em gestão de risco e desastre na amazônia - ppggrd'),
(gen_random_uuid(), 'programa de pós-graduação em recursos hídricos - pprh'),
(gen_random_uuid(), 'programa de pós-graduação em mestrado profissional em rede nacional para o ensino de ciências ambientais - profciamb'),
(gen_random_uuid(), 'programa de pós-graduação em oceanografia - ppgoc'),
(gen_random_uuid(), 'programa de pós-graduação em letras - ppgl'),
(gen_random_uuid(), 'programa de pós-graduação comunicação, cultura e amazônia - ppgcom'),
(gen_random_uuid(), 'programa de pós graduação em letras - profletras'),
(gen_random_uuid(), 'programa de pós-graduação em arquitetura e urbanismo - ppgau'),
(gen_random_uuid(), 'programa de pós-graduação em ciência e tecnologia de alimentos - ppgctea'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia civil - ppgec'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia mecânica - ppgem'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia elétrica - ppgee'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia química - ppgeq'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia industrial - ppgei'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia de processos - ppgep'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia de recursos naturais da amazônia - proderna'),
(gen_random_uuid(), 'programa de pós-graduação em processos construtivos e saneamento urbano - ppcs'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia naval - ppgenav'),
(gen_random_uuid(), 'programa de pós-graduação em ciências do patrimônio cultural - ppgpatri'),
(gen_random_uuid(), 'programa de pós-graduação em engenharia sanitária e ambiental - ppgesa'),
(gen_random_uuid(), 'programa de pós-graduação em desenvolvimento sustentável do trópico úmido - ppgdstu'),
(gen_random_uuid(), 'programa de pós-graduação em agriculturas amazônicas - ppgaa'),
(gen_random_uuid(), 'programa de pós-graduação em currículo e gestão da escola básica - ppeb'),
(gen_random_uuid(), 'programa de pós-graduação em educação na amazônia - educanorte (rede)'),
(gen_random_uuid(), 'programa de pós-graduação em doenças tropicais - ppgdt'),
(gen_random_uuid(), 'programa de pós-graduação em saúde na amazônia - ppgsa'),
(gen_random_uuid(), 'programa de pós-graduação em gestão de recursos naturais e desenvolvimento local na amazônia - ppgedam'),
(gen_random_uuid(), 'programa de pós-graduação em oncologia e ciências médicas - ppgocm'),
(gen_random_uuid(), 'programa de pós-graduação em neurociências e comportamento - ppgnc'),
(gen_random_uuid(), 'programa de pós-graduação em psicologia (teoria e pesquisa do comportamento) - ppgtpc'),
(gen_random_uuid(), 'programa de pós-graduação em música - profmus');


INSERT INTO public.usuario(id_usuario, id_programa, nome, email, senha, tipo_perfil, flag_ativo)
VALUES
(gen_random_uuid(), 'a00e073b-a262-4cd5-b64b-0ee5d35b8455', 'João Silva', 'joao.silva@email.com', '$2a$10$xJwL5v5Jz5TZ9zQbQFzN3.QjWj6U9cKjvW7JkXr3V2mYhL1sS5XbO', 'administrador', TRUE),

(gen_random_uuid(), 'a00e073b-a262-4cd5-b64b-0ee5d35b8455', 'Maria Oliveira', 'maria.oliveira@email.com', '$2a$10$yH9sL2pP8qR3tW4eF6gV7.uJ8kI0lM2nB3vC4d5fG6hJ7kL9mN1oP', 'administrador', TRUE),

-- Auditores
(gen_random_uuid(), 'a00e073b-a262-4cd5-b64b-0ee5d35b8455', 'Carlos Pereira', 'carlos.pereira@email.com', '$2a$10$zK8lM9nO0pQ1rS2tU3vW4.xY5zA6B7c8D9eF0gH1iJ2kL3mN4oP5q', 'auditor', TRUE),

(gen_random_uuid(), 'a00e073b-a262-4cd5-b64b-0ee5d35b8455', 'Ana Santos', 'ana.santos@email.com', '$2a$10$aB1cD2eF3gH4iJ5kL6mN7.oP8qR9sT0uV1wX2yZ3aB4cD5eF6gH7i', 'auditor', FALSE),

-- Pesquisadores
(gen_random_uuid(), 'a00e073b-a262-4cd5-b64b-0ee5d35b8455', 'Pedro Costa', 'pedro.costa@email.com', '$2a$10$jK8lM9nO0pQ1rS2tU3vW4.xY5zA6B7c8D9eF0gH1iJ2kL3mN4oP5q', 'pesquisador', TRUE),

(gen_random_uuid(), 'a00e073b-a262-4cd5-b64b-0ee5d35b8455', 'Luísa Fernandes', 'luisa.fernandes@email.com', '$2a$10$bC1dE2fG3hI4jK5lM6nO7.pQ8rS9tU0vW1xY2zA3B4cD5eF6gH7iJ', 'pesquisador', TRUE),

(gen_random_uuid(), 'a00e073b-a262-4cd5-b64b-0ee5d35b8455', 'Rafael Almeida', 'rafael.almeida@email.com', '$2a$10$cD1eF2gH3iJ4kL5mN6oP7.qR8sT9uV0wX1yZ2aB3cD4eF5gH6iJ7k', 'pesquisador', FALSE),

-- Outros exemplos variados
(gen_random_uuid(), 'a00e073b-a262-4cd5-b64b-0ee5d35b8455', 'Mariana Gonçalves', 'mariana.goncalves@email.com', '$2a$10$dE1fG2hI3jK4lM5nO6pP7.qR8sT9uV0wX1yZ2aB3cD4eF5gH6iJ7kL', 'administrador', FALSE),

(gen_random_uuid(), 'a00e073b-a262-4cd5-b64b-0ee5d35b8455', 'Antônio Nunes', 'antonio.nunes@email.com', '$2a$10$eF1gH2iJ3kL4mN5oP6qR7.sT8uV9wX0yZ1aB2cD3eF4gH5iJ6kL7m', 'auditor', TRUE);