name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  frontend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run linter
        working-directory: frontend
        run: npm run lint 

      - name: Run prettier
        working-directory: frontend
        run: npm run format

      - name: Build Dockerfile
        working-directory: frontend
        run: |
          if [ -f "Dockerfile" ]; then
            echo "Dockerfile found. Building the Docker image..."
            docker build -t your-image-name:latest .
          else
            echo "No Dockerfile found. Skipping Docker build."
          fi
        env:
          DOCKER_BUILDKIT: 1
