name: Prod CI Workflow

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile.prod
        push: true
        # Construct the tag dynamically
        tags: ghcr.io/${{ github.repository_owner }}/${{ secrets.BACKEND_IMAGE }}:${{ github.sha }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ secrets.BACKEND_IMAGE }}:latest
        cache-to: type=inline

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.prod
        push: true
        # Construct the tag dynamically
        tags: ghcr.io/${{ github.repository_owner }}/${{ secrets.FRONTEND_IMAGE }}:${{ github.sha }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ secrets.FRONTEND_IMAGE }}:latest
        cache-to: type=inline

    - name: SSH and Deploy with Docker Compose
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/AcadMap
          git pull origin main
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "BACKEND_IMAGE_TAG=${{ github.sha }}" > .env
          echo "FRONTEND_IMAGE_TAG=${{ github.sha }}" >> .env
          echo "REGISTRY_USER=${{ github.repository_owner }}" >> .env
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --remove-orphans --build
          docker image prune -af
